# Generated by Django 5.1.15 on 2026-07-09 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL segment. Changing it after publishing breaks existing links.', max_length=200, unique=True)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate, help_text='Drives ordering. A future date keeps the post hidden.')),
                ('icon', models.CharField(default='📰', help_text='A single emoji.', max_length=8)),
                ('tag_uz', models.CharField(blank=True, default='', max_length=60)),
                ('tag_ru', models.CharField(blank=True, default='', max_length=60)),
                ('tag_en', models.CharField(blank=True, default='', max_length=60)),
                ('title_uz', models.CharField(blank=True, default='', max_length=250)),
                ('title_ru', models.CharField(blank=True, default='', max_length=250)),
                ('title_en', models.CharField(blank=True, default='', max_length=250)),
                ('excerpt_uz', models.TextField(blank=True, default='')),
                ('excerpt_ru', models.TextField(blank=True, default='')),
                ('excerpt_en', models.TextField(blank=True, default='')),
                ('body_uz', models.TextField(blank=True, default='', help_text='Blank line = new paragraph.')),
                ('body_ru', models.TextField(blank=True, default='', help_text='Blank line = new paragraph.')),
                ('body_en', models.TextField(blank=True, default='', help_text='Blank line = new paragraph.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_on', '-pk'],
                'indexes': [models.Index(fields=['-published_on'], name='news_articl_publish_68fac8_idx')],
            },
        ),
    ]
