# Generated by Django 5.1.15 on 2026-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_on', '-pk'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
