# Generated by Django 6.0.7 on 2026-07-20 17:11

import django.db.models.deletion
import news.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='JPEG, PNG, WebP or AVIF, up to 5 MB.', upload_to='news/%Y/%m/', validators=[news.validators.validate_image_upload])),
                ('size', models.CharField(choices=[('full', 'Full width'), ('half', 'Half width'), ('thumb', 'Thumbnail')], default='full', help_text='How wide this photo renders in the article.', max_length=8)),
                ('alt_uz', models.CharField(blank=True, default='', max_length=200)),
                ('alt_ru', models.CharField(blank=True, default='', max_length=200)),
                ('alt_en', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.article')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
