# Generated by Django 5.1.15 on 2026-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, default='', max_length=200)),
                ('name_ru', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('short_uz', models.CharField(blank=True, default='', max_length=100)),
                ('short_ru', models.CharField(blank=True, default='', max_length=100)),
                ('short_en', models.CharField(blank=True, default='', max_length=100)),
                ('tagline_uz', models.CharField(blank=True, default='', max_length=250)),
                ('tagline_ru', models.CharField(blank=True, default='', max_length=250)),
                ('tagline_en', models.CharField(blank=True, default='', max_length=250)),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('address_uz', models.CharField(blank=True, default='', max_length=250)),
                ('address_ru', models.CharField(blank=True, default='', max_length=250)),
                ('address_en', models.CharField(blank=True, default='', max_length=250)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
