# Generated by Django 5.1.15 on 2026-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Social link', 'verbose_name_plural': 'Social links'},
        ),
    ]
