# Generated by Django 5.1.15 on 2026-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecturenode',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Architecture node', 'verbose_name_plural': 'Architecture nodes'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='functionalblock',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Functional block', 'verbose_name_plural': 'Functional blocks'},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Highlight', 'verbose_name_plural': 'Highlights'},
        ),
        migrations.AlterModelOptions(
            name='mechanismstep',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Mechanism step', 'verbose_name_plural': 'Mechanism steps'},
        ),
        migrations.AlterModelOptions(
            name='mediafeature',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Media feature', 'verbose_name_plural': 'Media features'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='roadmapstage',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Roadmap stage', 'verbose_name_plural': 'Roadmap stages'},
        ),
        migrations.AlterModelOptions(
            name='stakeholdervalue',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Stakeholder value', 'verbose_name_plural': 'Stakeholder values'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Stat', 'verbose_name_plural': 'Stats'},
        ),
        migrations.AlterModelOptions(
            name='strategicrole',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Strategic role', 'verbose_name_plural': 'Strategic roles'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Value', 'verbose_name_plural': 'Values'},
        ),
    ]
