# Generated by Django 5.1.15 on 2026-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('locale', models.CharField(blank=True, default='', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Recorded for abuse investigation only.', null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once someone has replied.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_sub_created_29e65e_idx')],
            },
        ),
    ]
