# Generated by Django 5.1.15 on 2026-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
    ]
