# Generated by Django 6.0.7 on 2026-07-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_submission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
