# Generated by Django 5.1.15 on 2026-07-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('slug', models.SlugField(blank=True, help_text='Left blank, this is generated from the English name.', max_length=200, unique=True)),
                ('name_uz', models.CharField(blank=True, default='', max_length=250)),
                ('name_ru', models.CharField(blank=True, default='', max_length=250)),
                ('name_en', models.CharField(max_length=250)),
                ('activity_uz', models.TextField(blank=True, default='')),
                ('activity_ru', models.TextField(blank=True, default='')),
                ('activity_en', models.TextField(blank=True, default='')),
                ('chairman', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('title_uz', models.CharField(blank=True, default='', max_length=150)),
                ('title_ru', models.CharField(blank=True, default='', max_length=150)),
                ('title_en', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('icon', models.CharField(help_text='A single emoji, e.g. 🎓', max_length=8)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc_uz', models.TextField(blank=True, default='')),
                ('desc_ru', models.TextField(blank=True, default='')),
                ('desc_en', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', help_text="Public site. Leave blank to show the 'In development' badge.")),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('icon', models.CharField(help_text='A single emoji, e.g. ⚖️', max_length=8)),
                ('name_uz', models.CharField(blank=True, default='', max_length=200)),
                ('name_ru', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('desc_uz', models.TextField(blank=True, default='')),
                ('desc_ru', models.TextField(blank=True, default='')),
                ('desc_en', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('name', models.CharField(help_text='Used when no override is set.', max_length=150)),
                ('name_uz', models.CharField(blank=True, default='', max_length=150)),
                ('name_ru', models.CharField(blank=True, default='', max_length=150)),
                ('name_en', models.CharField(blank=True, default='', max_length=150)),
                ('url', models.URLField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='catalog.partnergroup')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
    ]
