# Generated by Django 5.1.15 on 2026-07-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Partner group', 'verbose_name_plural': 'Partner groups'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
